@Library('mylibrary')_
node('built-in')
{
    stage('Download')
    {
        cicd.gitDownload("Maven")
    }
    stage('Build')
    {
        cicd.buildArtifact()
    }
    stage('Deploy')
    {
        cicd.deployTomcat("172.31.22.88","testapp2")
    }
    stage('Testing')
    {
        cicd.gitDownload("FunctionalTesting")
        cicd.runSelenium()
    }
    stage('Delivery')
    {
        cicd.deployTomcat("172.31.26.195","prodapp2")
    }
}
