@Library('mylibrary')_
node('built-in')
{
    stage('Download')
    {
        cicd.gitDownload("Maven")
    }
    stage('Build')
    {
        cicd.buildArtifact()
    }
    stage('Deploy')
    {
        cicd.deployTomcat("ScriptedPipelineSharedLibraries","172.31.22.88","testapp2")
    }
    stage('Testing')
    {
        cicd.gitDownload("FunctionalTesting")
        cicd.runSelenium("ScriptedPipelineSharedLibraries")
    }
    stage('Delivery')
    {
        cicd.deployTomcat("SriptedPipelineSharedLibraries","172.31.26.195","prodapp2")
    }
}
